spring:
 application:
   name: billingservice
server:
     port: 0
     #running multiple instances 
eureka:
  client:
    register-with-eureka: true
    #service should register with registry
    fetch-registry: true
    service-url:
         defaultZone: http://localhost:8761/eureka
         #where the registry service is running
         #eureka : name
  instance: 
    hostname: localhost   

